plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.5'
}

group = 'cn.tesseract'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven {
        url = "https://dl.google.com/dl/android/maven2/"
    }
}

dependencies {
    compileOnly project(':pre')
    compileOnly files("libs/android.jar")
    compileOnly files("libs/bak/classes_transformed.jar")
    implementation 'com.google.code.gson:gson:2.12.1'

}

tasks.register('jar2dex', Exec) {
    commandLine 'java', '-cp', 'D:\\build-tools\\34.0.0\\lib\\d8.jar', 'com.android.tools.r8.D8', 'classes.jar', "--min-api", "28"
    workingDir 'libs'
}

tasks.register('buildAPK', Exec) {
    commandLine 'D:\\build-tools\\34.0.0\\aapt.exe', 'a', 'base.apk', 'classes.dex'
    workingDir 'libs'
}

tasks.register('signAPK', Exec) {
    commandLine 'java', '-jar', 'D:\\build-tools\\34.0.0\\lib\\apksigner.jar', 'sign', '--ks', 'dragonfly.jks', '--ks-pass', 'pass:tesseract', '--key-pass', 'pass:tesseract', 'base.apk'
    workingDir 'libs'
}


tasks.register('installAPK', Exec) {
    commandLine 'D:\\platform-tools\\adb.exe', 'install', '-d', 'base.apk'
    workingDir 'libs'
}

tasks.register('run') {
    dependsOn shadowJar
    doLast {
        project(':pre').getTasksByName("transform", false).getAt(0).exec()
        jar2dex.exec()
        buildAPK.exec()
        signAPK.exec()
        installAPK.exec()
    }
}